version: "1"
rules:                      # Array of rules
  - base: develop            # Required. Target branch
    upstream: Brewtarget:develop    # Required. Must be in the same fork network.
    mergeMethod: rebase  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
label: ":arrow_heading_down: pull"  # Optional
