FROM archlinux/base
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Brewtarget Archlinux Devel version:- ${VERSION} Build-date:- ${BUILD_DATE}"

ENV TZ=Australia/Melbourne
WORKDIR /app

RUN pacman -Sy && pacman -S -y --noconfirm --needed \
    cmake \
    base-devel \
    sed \
    qt5-multimedia \
    qt5-svg \
    qt5-tools \
    qt5-webkit

ADD ./ /app/brewtarget
ADD ./docker/arch /app/arch
RUN useradd -m abc
RUN echo 'abc ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN echo $VERSION > /app/arch/VERSION
RUN chown -R abc:abc /app
USER abc
RUN /app/arch/build.sh
