FROM ubuntu:18.04
ENV TZ=Australia/Melbourne
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libqt5webkit5-dev \
    libqt5sql5-sqlite \
    libqt5svg5 \
    libqt5svg5-dev \
    libqt5multimedia5-plugins \
    qtbase5-dev \
    qttools5-dev \
    qttools5-dev-tools \
    qtmultimedia5-dev \
    rpm
ADD ./ /app/brewtarget
RUN /app/brewtarget/docker/ubuntu1804/build.sh
