FROM lsiobase/guacgui

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Brewtarget Devel version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="cgspeck"
ENV APPNAME="Brewtarget"

RUN \
  echo "**** install deps ****" && \
  apt-get update && \
  apt-get install -qy --no-install-recommends \
    # this section is prescribed by the .dpkg package!
    # libphonon4 \
    # libphonon4qt5-4 \
    # libqt4-dbus \
    # libqt4-network \
    # libqt4-svg \
    # libqtwebkit4 \
    # libqt4-xml \
    # libqtcore4 \
    # libqtgui4 \
    # phonon \
    # this section is what is actually used
    libqt5dbus5 \
    libqt5network5 \
    libqt5multimedia5 \
    libqt5printsupport5 \
    libqt5webkit5 \
    libqt5sql5 \
    libqt5xml5 \
    libqt5sql5-sqlite \
    libqt5xml5 \
    libqt5core5a \
    libqt5gui5 \
    libqt5sql5-psql \
    libqt5svg5 \
    wget && \
  echo "**** clean up ****" && \
  rm -rf \
  /tmp/* \
  /var/lib/apt/lists/* \
  /var/tmp/*

# add local files
COPY /docker/guacgui /
RUN chmod +x /usr/bin/setup-brewtarget
RUN /usr/bin/setup-brewtarget $VERSION

RUN mkdir /brewtarget
RUN chown abc:abc /brewtarget

# ports and volumes
EXPOSE 3389
VOLUME /brewtarget
VOLUME /config
