FROM lsiobase/guacgui

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Brewtarget Devel version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="cgspeck"
ENV APPNAME="Brewtarget"

RUN \
  echo "**** install deps ****" && \
  apt-get update && \
  apt-get install -qy --no-install-recommends \
    libphonon4 \
    libqt4-dbus \
    libqt4-network \
    libqt4-svg \
    libqtwebkit4 \
    libqt4-xml \
    libqt5multimedia5 \
    libqt5printsupport5 \
    libqt5sql5 \
    libqt5xml5 \
    libqtcore4 \
    libqtgui4 \
    phonon \
    wget && \
  echo "**** clean up ****" && \
  rm -rf \
  /tmp/* \
  /var/lib/apt/lists/* \
  /var/tmp/*

# add local files
COPY /docker/guacgui /
RUN chmod +x /usr/bin/setup-brewtarget
RUN /usr/bin/setup-brewtarget $VERSION

# ports and volumes
EXPOSE 3389
VOLUME /config

