#############################################################################
# Makefile for building: brewtarget
# Generated by qmake (2.01a) (Qt 4.4.0) on: Fri Feb 20 15:29:19 2009
# Project:  brewtarget.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile brewtarget.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = database.cpp \
		BeerColorWidget.cpp \
		equipment.cpp \
		fermentable.cpp \
		FermentableEditor.cpp \
		FermentableDialog.cpp \
		FermentableTableModel.cpp \
		FermentableTableWidget.cpp \
		guitest.cpp \
		hop.cpp \
		hoputilization.cpp \
		HopDialog.cpp \
		HopEditor.cpp \
		HopTableModel.cpp \
		HopTableWidget.cpp \
		MainWindow.cpp \
		mash.cpp \
		mashstep.cpp \
		MashStepTableModel.cpp \
		MashStepTableWidget.cpp \
		matrix.cpp \
		misc.cpp \
		MiscEditor.cpp \
		MiscDialog.cpp \
		MiscTableModel.cpp \
		MiscTableWidget.cpp \
		observable.cpp \
		observer.cpp \
		recipe.cpp \
		RecipeComboBox.cpp \
		stringparsing.cpp \
		style.cpp \
		unit.cpp \
		water.cpp \
		WaterTableModel.cpp \
		WaterTableWidget.cpp \
		xml.cpp \
		xmlnode.cpp \
		xmltree.cpp \
		yeast.cpp \
		YeastDialog.cpp \
		YeastTableModel.cpp \
		YeastTableWidget.cpp moc_BeerColorWidget.cpp \
		moc_FermentableEditor.cpp \
		moc_FermentableDialog.cpp \
		moc_FermentableTableModel.cpp \
		moc_FermentableTableWidget.cpp \
		moc_HopDialog.cpp \
		moc_HopEditor.cpp \
		moc_HopTableModel.cpp \
		moc_HopTableWidget.cpp \
		moc_MainWindow.cpp \
		moc_MashStepTableModel.cpp \
		moc_MashStepTableWidget.cpp \
		moc_MiscEditor.cpp \
		moc_MiscDialog.cpp \
		moc_MiscTableModel.cpp \
		moc_MiscTableWidget.cpp \
		moc_RecipeComboBox.cpp \
		moc_WaterTableModel.cpp \
		moc_WaterTableWidget.cpp \
		moc_YeastDialog.cpp \
		moc_YeastTableModel.cpp \
		moc_YeastTableWidget.cpp
OBJECTS       = database.o \
		BeerColorWidget.o \
		equipment.o \
		fermentable.o \
		FermentableEditor.o \
		FermentableDialog.o \
		FermentableTableModel.o \
		FermentableTableWidget.o \
		guitest.o \
		hop.o \
		hoputilization.o \
		HopDialog.o \
		HopEditor.o \
		HopTableModel.o \
		HopTableWidget.o \
		MainWindow.o \
		mash.o \
		mashstep.o \
		MashStepTableModel.o \
		MashStepTableWidget.o \
		matrix.o \
		misc.o \
		MiscEditor.o \
		MiscDialog.o \
		MiscTableModel.o \
		MiscTableWidget.o \
		observable.o \
		observer.o \
		recipe.o \
		RecipeComboBox.o \
		stringparsing.o \
		style.o \
		unit.o \
		water.o \
		WaterTableModel.o \
		WaterTableWidget.o \
		xml.o \
		xmlnode.o \
		xmltree.o \
		yeast.o \
		YeastDialog.o \
		YeastTableModel.o \
		YeastTableWidget.o \
		moc_BeerColorWidget.o \
		moc_FermentableEditor.o \
		moc_FermentableDialog.o \
		moc_FermentableTableModel.o \
		moc_FermentableTableWidget.o \
		moc_HopDialog.o \
		moc_HopEditor.o \
		moc_HopTableModel.o \
		moc_HopTableWidget.o \
		moc_MainWindow.o \
		moc_MashStepTableModel.o \
		moc_MashStepTableWidget.o \
		moc_MiscEditor.o \
		moc_MiscDialog.o \
		moc_MiscTableModel.o \
		moc_MiscTableWidget.o \
		moc_RecipeComboBox.o \
		moc_WaterTableModel.o \
		moc_WaterTableWidget.o \
		moc_YeastDialog.o \
		moc_YeastTableModel.o \
		moc_YeastTableWidget.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		brewtarget.pro
QMAKE_TARGET  = brewtarget
DESTDIR       = 
TARGET        = brewtarget

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_aboutDialog.h ui_mainWindow.h ui_miscEditor.h ui_fermentableEditor.h ui_fermentableDialog.h ui_hopDialog.h ui_hopEditor.h ui_miscDialog.h ui_yeastDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: brewtarget.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile brewtarget.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile brewtarget.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/brewtarget1.0.0 || $(MKDIR) .tmp/brewtarget1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/brewtarget1.0.0/ && $(COPY_FILE) --parents AboutDialog.h BeerColorWidget.h database.h equipment.h fermentable.h FermentableEditor.h FermentableDialog.h FermentableTableModel.h FermentableTableWidget.h hop.h hoputilization.h HopDialog.h HopEditor.h HopTableModel.h HopTableWidget.h MainWindow.h mash.h mashstep.h MashStepTableModel.h MashStepTableWidget.h matrix.h misc.h MiscEditor.h MiscDialog.h MiscTableModel.h MiscTableWidget.h observable.h recipe.h RecipeComboBox.h stringparsing.h style.h unit.h water.h WaterTableModel.h WaterTableWidget.h xml.h xmlnode.h xmltree.h yeast.h YeastDialog.h YeastTableModel.h YeastTableWidget.h .tmp/brewtarget1.0.0/ && $(COPY_FILE) --parents database.cpp BeerColorWidget.cpp equipment.cpp fermentable.cpp FermentableEditor.cpp FermentableDialog.cpp FermentableTableModel.cpp FermentableTableWidget.cpp guitest.cpp hop.cpp hoputilization.cpp HopDialog.cpp HopEditor.cpp HopTableModel.cpp HopTableWidget.cpp MainWindow.cpp mash.cpp mashstep.cpp MashStepTableModel.cpp MashStepTableWidget.cpp matrix.cpp misc.cpp MiscEditor.cpp MiscDialog.cpp MiscTableModel.cpp MiscTableWidget.cpp observable.cpp observer.cpp recipe.cpp RecipeComboBox.cpp stringparsing.cpp style.cpp unit.cpp water.cpp WaterTableModel.cpp WaterTableWidget.cpp xml.cpp xmlnode.cpp xmltree.cpp yeast.cpp YeastDialog.cpp YeastTableModel.cpp YeastTableWidget.cpp .tmp/brewtarget1.0.0/ && $(COPY_FILE) --parents aboutDialog.ui mainWindow.ui miscEditor.ui fermentableEditor.ui fermentableDialog.ui hopDialog.ui hopEditor.ui miscDialog.ui yeastDialog.ui .tmp/brewtarget1.0.0/ && (cd `dirname .tmp/brewtarget1.0.0` && $(TAR) brewtarget1.0.0.tar brewtarget1.0.0 && $(COMPRESS) brewtarget1.0.0.tar) && $(MOVE) `dirname .tmp/brewtarget1.0.0`/brewtarget1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/brewtarget1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_BeerColorWidget.cpp moc_FermentableEditor.cpp moc_FermentableDialog.cpp moc_FermentableTableModel.cpp moc_FermentableTableWidget.cpp moc_HopDialog.cpp moc_HopEditor.cpp moc_HopTableModel.cpp moc_HopTableWidget.cpp moc_MainWindow.cpp moc_MashStepTableModel.cpp moc_MashStepTableWidget.cpp moc_MiscEditor.cpp moc_MiscDialog.cpp moc_MiscTableModel.cpp moc_MiscTableWidget.cpp moc_RecipeComboBox.cpp moc_WaterTableModel.cpp moc_WaterTableWidget.cpp moc_YeastDialog.cpp moc_YeastTableModel.cpp moc_YeastTableWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_BeerColorWidget.cpp moc_FermentableEditor.cpp moc_FermentableDialog.cpp moc_FermentableTableModel.cpp moc_FermentableTableWidget.cpp moc_HopDialog.cpp moc_HopEditor.cpp moc_HopTableModel.cpp moc_HopTableWidget.cpp moc_MainWindow.cpp moc_MashStepTableModel.cpp moc_MashStepTableWidget.cpp moc_MiscEditor.cpp moc_MiscDialog.cpp moc_MiscTableModel.cpp moc_MiscTableWidget.cpp moc_RecipeComboBox.cpp moc_WaterTableModel.cpp moc_WaterTableWidget.cpp moc_YeastDialog.cpp moc_YeastTableModel.cpp moc_YeastTableWidget.cpp
moc_BeerColorWidget.cpp: BeerColorWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) BeerColorWidget.h -o moc_BeerColorWidget.cpp

moc_FermentableEditor.cpp: ui_fermentableEditor.h \
		fermentable.h \
		xmlnode.h \
		observable.h \
		FermentableEditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FermentableEditor.h -o moc_FermentableEditor.cpp

moc_FermentableDialog.cpp: ui_fermentableDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		HopEditor.h \
		ui_hopEditor.h \
		FermentableDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FermentableDialog.h -o moc_FermentableDialog.cpp

moc_FermentableTableModel.cpp: fermentable.h \
		xmlnode.h \
		observable.h \
		FermentableTableWidget.h \
		FermentableTableModel.h \
		FermentableTableModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FermentableTableModel.h -o moc_FermentableTableModel.cpp

moc_FermentableTableWidget.cpp: FermentableTableModel.h \
		fermentable.h \
		xmlnode.h \
		observable.h \
		FermentableTableWidget.h \
		FermentableTableWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FermentableTableWidget.h -o moc_FermentableTableWidget.cpp

moc_HopDialog.cpp: ui_hopDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		HopEditor.h \
		ui_hopEditor.h \
		HopDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) HopDialog.h -o moc_HopDialog.cpp

moc_HopEditor.cpp: ui_hopEditor.h \
		hop.h \
		xmlnode.h \
		observable.h \
		HopEditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) HopEditor.h -o moc_HopEditor.cpp

moc_HopTableModel.cpp: hop.h \
		xmlnode.h \
		observable.h \
		HopTableWidget.h \
		HopTableModel.h \
		HopTableModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) HopTableModel.h -o moc_HopTableModel.cpp

moc_HopTableWidget.cpp: HopTableModel.h \
		hop.h \
		xmlnode.h \
		observable.h \
		HopTableWidget.h \
		HopTableWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) HopTableWidget.h -o moc_HopTableWidget.cpp

moc_MainWindow.cpp: ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopEditor.h \
		ui_hopEditor.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_MashStepTableModel.cpp: mashstep.h \
		xmlnode.h \
		observable.h \
		MashStepTableWidget.h \
		MashStepTableModel.h \
		MashStepTableModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MashStepTableModel.h -o moc_MashStepTableModel.cpp

moc_MashStepTableWidget.cpp: MashStepTableModel.h \
		mashstep.h \
		xmlnode.h \
		observable.h \
		MashStepTableWidget.h \
		MashStepTableWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MashStepTableWidget.h -o moc_MashStepTableWidget.cpp

moc_MiscEditor.cpp: ui_miscEditor.h \
		misc.h \
		xmlnode.h \
		observable.h \
		MiscEditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MiscEditor.h -o moc_MiscEditor.cpp

moc_MiscDialog.cpp: ui_miscDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		HopEditor.h \
		ui_hopEditor.h \
		MiscDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MiscDialog.h -o moc_MiscDialog.cpp

moc_MiscTableModel.cpp: misc.h \
		xmlnode.h \
		observable.h \
		MiscTableWidget.h \
		MiscTableModel.h \
		MiscTableModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MiscTableModel.h -o moc_MiscTableModel.cpp

moc_MiscTableWidget.cpp: MiscTableModel.h \
		misc.h \
		xmlnode.h \
		observable.h \
		MiscTableWidget.h \
		MiscTableWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MiscTableWidget.h -o moc_MiscTableWidget.cpp

moc_RecipeComboBox.cpp: observable.h \
		recipe.h \
		xmlnode.h \
		style.h \
		misc.h \
		mash.h \
		mashstep.h \
		hop.h \
		fermentable.h \
		equipment.h \
		yeast.h \
		water.h \
		database.h \
		RecipeComboBox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) RecipeComboBox.h -o moc_RecipeComboBox.cpp

moc_WaterTableModel.cpp: water.h \
		xmlnode.h \
		observable.h \
		WaterTableWidget.h \
		WaterTableModel.h \
		WaterTableModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) WaterTableModel.h -o moc_WaterTableModel.cpp

moc_WaterTableWidget.cpp: WaterTableModel.h \
		water.h \
		xmlnode.h \
		observable.h \
		WaterTableWidget.h \
		WaterTableWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) WaterTableWidget.h -o moc_WaterTableWidget.cpp

moc_YeastDialog.cpp: ui_yeastDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		HopEditor.h \
		ui_hopEditor.h \
		YeastDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YeastDialog.h -o moc_YeastDialog.cpp

moc_YeastTableModel.cpp: yeast.h \
		xmlnode.h \
		observable.h \
		YeastTableWidget.h \
		YeastTableModel.h \
		YeastTableModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YeastTableModel.h -o moc_YeastTableModel.cpp

moc_YeastTableWidget.cpp: YeastTableModel.h \
		yeast.h \
		xmlnode.h \
		observable.h \
		YeastTableWidget.h \
		YeastTableWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YeastTableWidget.h -o moc_YeastTableWidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aboutDialog.h ui_mainWindow.h ui_miscEditor.h ui_fermentableEditor.h ui_fermentableDialog.h ui_hopDialog.h ui_hopEditor.h ui_miscDialog.h ui_yeastDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aboutDialog.h ui_mainWindow.h ui_miscEditor.h ui_fermentableEditor.h ui_fermentableDialog.h ui_hopDialog.h ui_hopEditor.h ui_miscDialog.h ui_yeastDialog.h
ui_aboutDialog.h: aboutDialog.ui
	/usr/bin/uic-qt4 aboutDialog.ui -o ui_aboutDialog.h

ui_mainWindow.h: mainWindow.ui \
		FermentableTableWidget.h \
		HopTableWidget.h \
		MiscTableWidget.h \
		RecipeComboBox.h \
		YeastTableWidget.h \
		FermentableTableModel.h \
		fermentable.h \
		xmlnode.h \
		observable.h \
		FermentableTableWidget.h \
		HopTableModel.h \
		hop.h \
		xmlnode.h \
		observable.h \
		HopTableWidget.h \
		MiscTableModel.h \
		misc.h \
		xmlnode.h \
		observable.h \
		MiscTableWidget.h \
		observable.h \
		recipe.h \
		xmlnode.h \
		style.h \
		misc.h \
		mash.h \
		mashstep.h \
		hop.h \
		fermentable.h \
		equipment.h \
		yeast.h \
		water.h \
		database.h \
		YeastTableModel.h \
		yeast.h \
		xmlnode.h \
		observable.h \
		YeastTableWidget.h
	/usr/bin/uic-qt4 mainWindow.ui -o ui_mainWindow.h

ui_miscEditor.h: miscEditor.ui
	/usr/bin/uic-qt4 miscEditor.ui -o ui_miscEditor.h

ui_fermentableEditor.h: fermentableEditor.ui
	/usr/bin/uic-qt4 fermentableEditor.ui -o ui_fermentableEditor.h

ui_fermentableDialog.h: fermentableDialog.ui \
		FermentableTableWidget.h \
		FermentableTableModel.h \
		fermentable.h \
		xmlnode.h \
		observable.h \
		FermentableTableWidget.h
	/usr/bin/uic-qt4 fermentableDialog.ui -o ui_fermentableDialog.h

ui_hopDialog.h: hopDialog.ui \
		HopTableWidget.h \
		HopTableModel.h \
		hop.h \
		xmlnode.h \
		observable.h \
		HopTableWidget.h
	/usr/bin/uic-qt4 hopDialog.ui -o ui_hopDialog.h

ui_hopEditor.h: hopEditor.ui
	/usr/bin/uic-qt4 hopEditor.ui -o ui_hopEditor.h

ui_miscDialog.h: miscDialog.ui \
		MiscTableWidget.h \
		MiscTableModel.h \
		misc.h \
		xmlnode.h \
		observable.h \
		MiscTableWidget.h
	/usr/bin/uic-qt4 miscDialog.ui -o ui_miscDialog.h

ui_yeastDialog.h: yeastDialog.ui \
		YeastTableWidget.h \
		YeastTableModel.h \
		yeast.h \
		xmlnode.h \
		observable.h \
		YeastTableWidget.h
	/usr/bin/uic-qt4 yeastDialog.ui -o ui_yeastDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

database.o: database.cpp database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		observable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		xmltree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

BeerColorWidget.o: BeerColorWidget.cpp BeerColorWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BeerColorWidget.o BeerColorWidget.cpp

equipment.o: equipment.cpp xmlnode.h \
		stringparsing.h \
		equipment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o equipment.o equipment.cpp

fermentable.o: fermentable.cpp fermentable.h \
		xmlnode.h \
		observable.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fermentable.o fermentable.cpp

FermentableEditor.o: FermentableEditor.cpp FermentableEditor.h \
		ui_fermentableEditor.h \
		fermentable.h \
		xmlnode.h \
		observable.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FermentableEditor.o FermentableEditor.cpp

FermentableDialog.o: FermentableDialog.cpp FermentableDialog.h \
		ui_fermentableDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopEditor.h \
		ui_hopEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FermentableDialog.o FermentableDialog.cpp

FermentableTableModel.o: FermentableTableModel.cpp observable.h \
		fermentable.h \
		xmlnode.h \
		FermentableTableModel.h \
		FermentableTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FermentableTableModel.o FermentableTableModel.cpp

FermentableTableWidget.o: FermentableTableWidget.cpp FermentableTableModel.h \
		fermentable.h \
		xmlnode.h \
		observable.h \
		FermentableTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FermentableTableWidget.o FermentableTableWidget.cpp

guitest.o: guitest.cpp MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		HopEditor.h \
		ui_hopEditor.h \
		xmltree.h \
		unit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guitest.o guitest.cpp

hop.o: hop.cpp hop.h \
		xmlnode.h \
		observable.h \
		xml.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hop.o hop.cpp

hoputilization.o: hoputilization.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hoputilization.o hoputilization.cpp

HopDialog.o: HopDialog.cpp HopDialog.h \
		ui_hopDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		HopEditor.h \
		ui_hopEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HopDialog.o HopDialog.cpp

HopEditor.o: HopEditor.cpp HopEditor.h \
		ui_hopEditor.h \
		hop.h \
		xmlnode.h \
		observable.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HopEditor.o HopEditor.cpp

HopTableModel.o: HopTableModel.cpp hop.h \
		xmlnode.h \
		observable.h \
		HopTableModel.h \
		HopTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HopTableModel.o HopTableModel.cpp

HopTableWidget.o: HopTableWidget.cpp HopTableModel.h \
		hop.h \
		xmlnode.h \
		observable.h \
		HopTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HopTableWidget.o HopTableWidget.cpp

MainWindow.o: MainWindow.cpp FermentableEditor.h \
		ui_fermentableEditor.h \
		fermentable.h \
		xmlnode.h \
		observable.h \
		MiscEditor.h \
		ui_miscEditor.h \
		misc.h \
		HopEditor.h \
		ui_hopEditor.h \
		hop.h \
		YeastTableModel.h \
		yeast.h \
		YeastTableWidget.h \
		MiscTableModel.h \
		MiscTableWidget.h \
		style.h \
		recipe.h \
		mash.h \
		mashstep.h \
		equipment.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		database.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

mash.o: mash.cpp xmlnode.h \
		stringparsing.h \
		mash.h \
		mashstep.h \
		observable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mash.o mash.cpp

mashstep.o: mashstep.cpp xmlnode.h \
		stringparsing.h \
		mashstep.h \
		observable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mashstep.o mashstep.cpp

MashStepTableModel.o: MashStepTableModel.cpp mashstep.h \
		xmlnode.h \
		observable.h \
		MashStepTableModel.h \
		MashStepTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MashStepTableModel.o MashStepTableModel.cpp

MashStepTableWidget.o: MashStepTableWidget.cpp MashStepTableModel.h \
		mashstep.h \
		xmlnode.h \
		observable.h \
		MashStepTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MashStepTableWidget.o MashStepTableWidget.cpp

matrix.o: matrix.cpp matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matrix.o matrix.cpp

misc.o: misc.cpp misc.h \
		xmlnode.h \
		observable.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o misc.o misc.cpp

MiscEditor.o: MiscEditor.cpp misc.h \
		xmlnode.h \
		observable.h \
		MiscEditor.h \
		ui_miscEditor.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MiscEditor.o MiscEditor.cpp

MiscDialog.o: MiscDialog.cpp MiscDialog.h \
		ui_miscDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopDialog.h \
		ui_hopDialog.h \
		YeastDialog.h \
		ui_yeastDialog.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		MiscEditor.h \
		ui_miscEditor.h \
		HopEditor.h \
		ui_hopEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MiscDialog.o MiscDialog.cpp

MiscTableModel.o: MiscTableModel.cpp misc.h \
		xmlnode.h \
		observable.h \
		MiscTableModel.h \
		MiscTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MiscTableModel.o MiscTableModel.cpp

MiscTableWidget.o: MiscTableWidget.cpp MiscTableWidget.h \
		MiscTableModel.h \
		misc.h \
		xmlnode.h \
		observable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MiscTableWidget.o MiscTableWidget.cpp

observable.o: observable.cpp observable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o observable.o observable.cpp

observer.o: observer.cpp observable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o observer.o observer.cpp

recipe.o: recipe.cpp xmlnode.h \
		stringparsing.h \
		recipe.h \
		style.h \
		observable.h \
		misc.h \
		mash.h \
		mashstep.h \
		hop.h \
		fermentable.h \
		equipment.h \
		yeast.h \
		water.h \
		hoputilization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recipe.o recipe.cpp

RecipeComboBox.o: RecipeComboBox.cpp database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		observable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		RecipeComboBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RecipeComboBox.o RecipeComboBox.cpp

stringparsing.o: stringparsing.cpp stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stringparsing.o stringparsing.cpp

style.o: style.cpp xmlnode.h \
		stringparsing.h \
		style.h \
		observable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o style.o style.cpp

unit.o: unit.cpp unit.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unit.o unit.cpp

water.o: water.cpp stringparsing.h \
		water.h \
		xmlnode.h \
		observable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o water.o water.cpp

WaterTableModel.o: WaterTableModel.cpp observable.h \
		WaterTableModel.h \
		water.h \
		xmlnode.h \
		WaterTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaterTableModel.o WaterTableModel.cpp

WaterTableWidget.o: WaterTableWidget.cpp WaterTableModel.h \
		water.h \
		xmlnode.h \
		observable.h \
		WaterTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaterTableWidget.o WaterTableWidget.cpp

xml.o: xml.cpp xml.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xml.o xml.cpp

xmlnode.o: xmlnode.cpp stringparsing.h \
		xmlnode.h \
		xml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlnode.o xmlnode.cpp

xmltree.o: xmltree.cpp xmlnode.h \
		xmltree.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmltree.o xmltree.cpp

yeast.o: yeast.cpp yeast.h \
		xmlnode.h \
		observable.h \
		stringparsing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yeast.o yeast.cpp

YeastDialog.o: YeastDialog.cpp YeastDialog.h \
		ui_yeastDialog.h \
		observable.h \
		database.h \
		equipment.h \
		xmlnode.h \
		fermentable.h \
		hop.h \
		mash.h \
		mashstep.h \
		misc.h \
		recipe.h \
		style.h \
		yeast.h \
		water.h \
		MainWindow.h \
		ui_mainWindow.h \
		FermentableDialog.h \
		ui_fermentableDialog.h \
		FermentableEditor.h \
		ui_fermentableEditor.h \
		HopDialog.h \
		ui_hopDialog.h \
		MiscDialog.h \
		ui_miscDialog.h \
		MiscEditor.h \
		ui_miscEditor.h \
		AboutDialog.h \
		ui_aboutDialog.h \
		BeerColorWidget.h \
		HopEditor.h \
		ui_hopEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YeastDialog.o YeastDialog.cpp

YeastTableModel.o: YeastTableModel.cpp yeast.h \
		xmlnode.h \
		observable.h \
		YeastTableModel.h \
		YeastTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YeastTableModel.o YeastTableModel.cpp

YeastTableWidget.o: YeastTableWidget.cpp YeastTableModel.h \
		yeast.h \
		xmlnode.h \
		observable.h \
		YeastTableWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YeastTableWidget.o YeastTableWidget.cpp

moc_BeerColorWidget.o: moc_BeerColorWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BeerColorWidget.o moc_BeerColorWidget.cpp

moc_FermentableEditor.o: moc_FermentableEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FermentableEditor.o moc_FermentableEditor.cpp

moc_FermentableDialog.o: moc_FermentableDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FermentableDialog.o moc_FermentableDialog.cpp

moc_FermentableTableModel.o: moc_FermentableTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FermentableTableModel.o moc_FermentableTableModel.cpp

moc_FermentableTableWidget.o: moc_FermentableTableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FermentableTableWidget.o moc_FermentableTableWidget.cpp

moc_HopDialog.o: moc_HopDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HopDialog.o moc_HopDialog.cpp

moc_HopEditor.o: moc_HopEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HopEditor.o moc_HopEditor.cpp

moc_HopTableModel.o: moc_HopTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HopTableModel.o moc_HopTableModel.cpp

moc_HopTableWidget.o: moc_HopTableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HopTableWidget.o moc_HopTableWidget.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MashStepTableModel.o: moc_MashStepTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MashStepTableModel.o moc_MashStepTableModel.cpp

moc_MashStepTableWidget.o: moc_MashStepTableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MashStepTableWidget.o moc_MashStepTableWidget.cpp

moc_MiscEditor.o: moc_MiscEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MiscEditor.o moc_MiscEditor.cpp

moc_MiscDialog.o: moc_MiscDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MiscDialog.o moc_MiscDialog.cpp

moc_MiscTableModel.o: moc_MiscTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MiscTableModel.o moc_MiscTableModel.cpp

moc_MiscTableWidget.o: moc_MiscTableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MiscTableWidget.o moc_MiscTableWidget.cpp

moc_RecipeComboBox.o: moc_RecipeComboBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RecipeComboBox.o moc_RecipeComboBox.cpp

moc_WaterTableModel.o: moc_WaterTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WaterTableModel.o moc_WaterTableModel.cpp

moc_WaterTableWidget.o: moc_WaterTableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WaterTableWidget.o moc_WaterTableWidget.cpp

moc_YeastDialog.o: moc_YeastDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_YeastDialog.o moc_YeastDialog.cpp

moc_YeastTableModel.o: moc_YeastTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_YeastTableModel.o moc_YeastTableModel.cpp

moc_YeastTableWidget.o: moc_YeastTableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_YeastTableWidget.o moc_YeastTableWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

