.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BREWTARGET 1 "July 25, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
brewtarget \- Helps you brew beer.
.SH DESCRIPTION
Brewtarget is a Qt\-based beer recipe calculator to manage and help you create beer recipes. It has no command-line options.
.SH AUTHOR
Brewtarget was written by Philip G. Lee.
.PP
This manual page was written by Philip G. Lee <rocketman768@gmail.com>,
for the Debian project (and may be used by others).
