#! /bin/bash -e
if [[ -z "${TRAVIS_BUILD_NUMBER}" ]]; then
    TAG_NAME="v2.4.0-0(unknown)"
else
    TAG_NAME="v2.4.0-${TRAVIS_BUILD_NUMBER}"
fi

TARGET_COMMITISH=$(git rev-parse HEAD)
SHORT_HASH=$(git rev-parse --short HEAD)
